export const FEEDBACK_LIST_REQUEST = "FEEDBACK_LIST_REQUEST";
export const FEEDBACK_LIST_SUCCESS = "FEEDBACK_LIST_SUCCESS";
export const FEEDBACK_LIST_FAIL = "FEEDBACK_LIST_FAIL";

export const FEEDBACK_DETAILS_REQUEST = "FEEDBACK_DETAILS_REQUEST";
export const FEEDBACK_DETAILS_SUCCESS = "FEEDBACK_DETAILS_SUCCESS";
export const FEEDBACK_DETAILS_FAIL = "FEEDBACK_DETAILS_FAIL";

export const UPDATE_FEEDBACK_REQUEST = "UPDATE_FEEDBACK_REQUEST";
export const UPDATE_FEEDBACK_SUCCESS = "UPDATE_FEEDBACK_SUCCESS";
export const UPDATE_FEEDBACK_FAIL = "UPDATE_FEEDBACK_FAIL";

export const DELETE_FEEDBACK_REQUEST = "DELETE_FEEDBACK_REQUEST";
export const DELETE_FEEDBACK_SUCCESS = "DELETE_FEEDBACK_SUCCESS";
export const DELETE_FEEDBACK_FAIL = "DELETE_FEEDBACK_FAIL";

export const FILTER_FEEDBACKS = "FILTER_FEEDBACKS";

export const SET_SELECTED = "SET_SELECTED";

export const SORT_BY_MOST_UPVOTES = "SORT_BY_MOST_UPVOTES";
export const SORT_BY_LEAST_UPVOTES = "SORT_BY_LEAST_UPVOTES";
export const SORT_BY_MOST_COMMENTS = "SORT_BY_MOST_COMMENTS";
export const SORT_BY_LEAST_COMMENTS = "SORT_BY_LEAST_COMMENTS";
